# Generated by Django 4.2.16 on 2025-09-02 04:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="药品的通用名称或商品名称", max_length=100, verbose_name="药品名称"
                    ),
                ),
                (
                    "specification",
                    models.CharField(
                        blank=True,
                        help_text='药品规格，如"100mg*30片"',
                        max_length=100,
                        null=True,
                        verbose_name="药品规格",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True,
                        help_text="药品生产厂家名称",
                        max_length=100,
                        null=True,
                        verbose_name="生产厂家",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="药品有效期至日期", null=True, verbose_name="有效期"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="当前库存数量",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="药品数量",
                    ),
                ),
                (
                    "storage_conditions",
                    models.TextField(
                        blank=True,
                        help_text="药品存储要求，如温度、湿度、光照等条件",
                        null=True,
                        verbose_name="存储条件",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="药品图片的存储URL",
                        null=True,
                        verbose_name="药品图片URL",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="药品的详细描述信息",
                        null=True,
                        verbose_name="药品描述",
                    ),
                ),
                (
                    "medicine_type",
                    models.CharField(
                        choices=[
                            ("tablet", "片剂"),
                            ("capsule", "胶囊"),
                            ("liquid", "液体"),
                            ("injection", "注射剂"),
                            ("ointment", "软膏"),
                            ("drops", "滴剂"),
                            ("other", "其他"),
                        ],
                        default="tablet",
                        help_text="药品的剂型类型",
                        max_length=20,
                        verbose_name="药品类型",
                    ),
                ),
                (
                    "is_prescription",
                    models.BooleanField(
                        default=False, help_text="标识是否为处方药", verbose_name="是否为处方药"
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True,
                        help_text="药品生产批号",
                        max_length=50,
                        null=True,
                        verbose_name="药品批号",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, help_text="药品购买日期", null=True, verbose_name="购买日期"
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="药品购买价格",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="购买价格",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="记录创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="记录最后更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="药品所属用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to="users.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "药品",
                "verbose_name_plural": "药品",
                "db_table": "medicines",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user_id"], name="idx_medicines_user_id"),
                    models.Index(fields=["name"], name="idx_medicines_name"),
                    models.Index(
                        fields=["expiry_date"], name="idx_medicines_expiry_date"
                    ),
                    models.Index(
                        fields=["created_at"], name="idx_medicines_created_at"
                    ),
                    models.Index(fields=["medicine_type"], name="idx_medicines_type"),
                ],
            },
        ),
    ]
