# Generated by Django 4.2.16 on 2025-09-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="药品图片的存储URL",
                max_length=500,
                null=True,
                verbose_name="药品图片URL",
            ),
        ),
    ]
