# Generated by Django 4.2.16 on 2026-02-21 16:44

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0003_rename_image_url_to_image_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="description",
            field=apps.core.fields.EncryptedTextField(
                blank=True, help_text="药品的详细描述信息", null=True, verbose_name="药品描述"
            ),
        ),
    ]
