# Generated by Django 4.2.16 on 2025-09-02 04:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(help_text="实际就诊的日期", verbose_name="就诊日期"),
                ),
                (
                    "visit_time",
                    models.TimeField(
                        blank=True, help_text="具体的就诊时间", null=True, verbose_name="就诊时间"
                    ),
                ),
                (
                    "hospital",
                    models.CharField(
                        help_text="就诊的医院名称", max_length=100, verbose_name="医院名称"
                    ),
                ),
                (
                    "hospital_address",
                    models.CharField(
                        blank=True,
                        help_text="医院的详细地址",
                        max_length=200,
                        null=True,
                        verbose_name="医院地址",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="就诊的科室",
                        max_length=50,
                        null=True,
                        verbose_name="科室",
                    ),
                ),
                (
                    "doctor",
                    models.CharField(
                        blank=True,
                        help_text="接诊医生的姓名",
                        max_length=50,
                        null=True,
                        verbose_name="医生姓名",
                    ),
                ),
                (
                    "doctor_title",
                    models.CharField(
                        blank=True,
                        help_text="医生的职称，如主任医师、副主任医师等",
                        max_length=50,
                        null=True,
                        verbose_name="医生职称",
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("outpatient", "门诊"),
                            ("emergency", "急诊"),
                            ("inpatient", "住院"),
                            ("follow_up", "复诊"),
                            ("consultation", "会诊"),
                            ("physical_exam", "体检"),
                            ("vaccination", "疫苗接种"),
                        ],
                        default="outpatient",
                        help_text="就诊的类型",
                        max_length=20,
                        verbose_name="就诊类型",
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(
                        blank=True, help_text="患者的主要症状和不适", null=True, verbose_name="主诉"
                    ),
                ),
                (
                    "present_illness",
                    models.TextField(
                        blank=True, help_text="当前疾病的发展过程", null=True, verbose_name="现病史"
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(
                        blank=True, help_text="医生的诊断结果", null=True, verbose_name="诊断结果"
                    ),
                ),
                (
                    "diagnosis_code",
                    models.CharField(
                        blank=True,
                        help_text="ICD-10诊断代码",
                        max_length=20,
                        null=True,
                        verbose_name="诊断代码",
                    ),
                ),
                (
                    "treatment",
                    models.TextField(
                        blank=True,
                        help_text="医生制定的治疗方案",
                        null=True,
                        verbose_name="治疗方案",
                    ),
                ),
                (
                    "prescribed_medicines",
                    models.JSONField(
                        default=list, help_text="医生开具的药品列表", verbose_name="处方药品"
                    ),
                ),
                (
                    "examinations",
                    models.JSONField(
                        default=list, help_text="进行的检查项目列表", verbose_name="检查项目"
                    ),
                ),
                (
                    "examination_results",
                    models.TextField(
                        blank=True, help_text="各项检查的结果", null=True, verbose_name="检查结果"
                    ),
                ),
                (
                    "lab_results",
                    models.JSONField(
                        default=dict, help_text="化验检查的具体数值结果", verbose_name="化验结果"
                    ),
                ),
                (
                    "medical_orders",
                    models.TextField(
                        blank=True, help_text="医生的医嘱和建议", null=True, verbose_name="医嘱"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="就医过程中的备注和注意事项",
                        null=True,
                        verbose_name="注意事项",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="本次就医的总费用",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="总费用",
                    ),
                ),
                (
                    "insurance_coverage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="医保报销的金额",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="医保报销",
                    ),
                ),
                (
                    "self_pay_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="个人自费的金额",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="自费金额",
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, help_text="建议的复诊时间", null=True, verbose_name="复诊时间"
                    ),
                ),
                (
                    "follow_up_notes",
                    models.TextField(
                        blank=True, help_text="复诊的相关说明", null=True, verbose_name="复诊说明"
                    ),
                ),
                (
                    "symptom_score_before",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="就诊前症状严重程度评分（1-10分）",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="就诊前症状评分",
                    ),
                ),
                (
                    "symptom_score_after",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="就诊后症状改善程度评分（1-10分）",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="就诊后症状评分",
                    ),
                ),
                (
                    "satisfaction_score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="对本次就医的满意度评分（1-5分）",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="满意度评分",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "已预约"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                            ("no_show", "未到诊"),
                            ("rescheduled", "已改期"),
                        ],
                        default="completed",
                        help_text="就医记录的状态",
                        max_length=20,
                        verbose_name="就医状态",
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("routine", "常规"),
                            ("urgent", "紧急"),
                            ("emergency", "急诊"),
                            ("critical", "危重"),
                        ],
                        default="routine",
                        help_text="就医的紧急程度",
                        max_length=20,
                        verbose_name="紧急程度",
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        default=list, help_text="相关的医疗文件、报告等", verbose_name="相关文件"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="记录创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="记录最后更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="就医记录所属用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="users.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "就医记录",
                "verbose_name_plural": "就医记录",
                "db_table": "medical_records",
                "ordering": ["-visit_date", "-visit_time"],
                "indexes": [
                    models.Index(
                        fields=["user_id"], name="idx_medical_records_user_id"
                    ),
                    models.Index(
                        fields=["visit_date"], name="idx_medical_records_visit_date"
                    ),
                    models.Index(
                        fields=["hospital"], name="idx_medical_records_hospital"
                    ),
                    models.Index(
                        fields=["department"], name="idx_medical_records_department"
                    ),
                    models.Index(fields=["doctor"], name="idx_medical_records_doctor"),
                    models.Index(
                        fields=["visit_type"], name="idx_medical_records_visit_type"
                    ),
                    models.Index(fields=["status"], name="idx_medical_records_status"),
                    models.Index(
                        fields=["urgency"], name="idx_medical_records_urgency"
                    ),
                    models.Index(
                        fields=["user_id", "visit_date"],
                        name="idx_medical_records_user_date",
                    ),
                ],
            },
        ),
    ]
