# Generated by Django 4.2.16 on 2026-02-21 16:44

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medical_records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecord",
            name="diagnosis",
            field=apps.core.fields.EncryptedTextField(
                blank=True, help_text="医生的诊断结果", null=True, verbose_name="诊断结果"
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="medical_orders",
            field=apps.core.fields.EncryptedTextField(
                blank=True, help_text="医生的医嘱和建议", null=True, verbose_name="医嘱"
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="treatment",
            field=apps.core.fields.EncryptedTextField(
                blank=True, help_text="医生制定的治疗方案", null=True, verbose_name="治疗方案"
            ),
        ),
    ]
