# Generated by Django 4.2.16 on 2026-04-13 14:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MTMServiceCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_number",
                    models.CharField(
                        editable=False,
                        help_text="MTM 服务业务编号",
                        max_length=32,
                        unique=True,
                        verbose_name="服务编号",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待开始"),
                            ("interviewing", "问诊中"),
                            ("assessing", "评估中"),
                            ("intervening", "干预中"),
                            ("following_up", "随访中"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        help_text="MTM 服务当前所处的流程状态",
                        max_length=20,
                        verbose_name="服务状态",
                    ),
                ),
                (
                    "trigger_source",
                    models.CharField(
                        choices=[
                            ("manual", "手动发起"),
                            ("self_requested", "用户主动申请"),
                            ("adherence_alert", "依从性预警"),
                            ("followup_due", "复诊到期"),
                            ("polypharmacy", "多重用药"),
                            ("referral", "转介"),
                        ],
                        default="manual",
                        help_text="MTM 服务的触发来源",
                        max_length=20,
                        verbose_name="触发来源",
                    ),
                ),
                (
                    "service_goal",
                    models.TextField(
                        blank=True,
                        help_text="本次 MTM 服务的主要目标",
                        null=True,
                        verbose_name="服务目标",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="服务单层面的补充说明",
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="服务单正式建立或开始处理的时间",
                        verbose_name="启动时间",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="服务单完成的时间",
                        null=True,
                        verbose_name="完成时间",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "assigned_pharmacist",
                    models.ForeignKey(
                        blank=True,
                        help_text="当前负责该 MTM 服务的药师用户",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_mtm_service_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="主责药师",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="服务对应的患者用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mtm_service_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="患者",
                    ),
                ),
            ],
            options={
                "verbose_name": "MTM服务单",
                "verbose_name_plural": "MTM服务单",
                "db_table": "mtm_service_cases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MTMPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interventions",
                    models.JSONField(
                        default=list,
                        help_text="结构化干预措施列表",
                        verbose_name="干预措施",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("urgent", "紧急"),
                        ],
                        default="medium",
                        help_text="当前计划整体优先级",
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "patient_confirmation_status",
                    models.CharField(
                        choices=[
                            ("pending", "待确认"),
                            ("confirmed", "已确认"),
                            ("declined", "已拒绝"),
                        ],
                        default="pending",
                        help_text="患者对干预计划的确认状态",
                        max_length=20,
                        verbose_name="患者确认状态",
                    ),
                ),
                (
                    "patient_confirmation_notes",
                    models.TextField(
                        blank=True,
                        help_text="患者确认或拒绝时的补充说明",
                        null=True,
                        verbose_name="患者确认说明",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="患者确认时间",
                        null=True,
                        verbose_name="确认时间",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "service_case",
                    models.OneToOneField(
                        help_text="对应的 MTM 服务单",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan",
                        to="mtm.mtmservicecase",
                        verbose_name="服务单",
                    ),
                ),
            ],
            options={
                "verbose_name": "MTM干预计划",
                "verbose_name_plural": "MTM干预计划",
                "db_table": "mtm_plans",
            },
        ),
        migrations.CreateModel(
            name="MTMInterview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic_info_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="患者当前基础资料快照",
                        verbose_name="基本信息快照",
                    ),
                ),
                (
                    "medication_history",
                    models.JSONField(
                        default=list,
                        help_text="结构化的既往与当前用药信息",
                        verbose_name="用药史",
                    ),
                ),
                (
                    "allergy_history",
                    models.JSONField(
                        default=list,
                        help_text="结构化过敏史记录",
                        verbose_name="过敏史",
                    ),
                ),
                (
                    "lifestyle_info",
                    models.JSONField(
                        default=dict,
                        help_text="饮食、运动、睡眠等生活方式信息",
                        verbose_name="生活方式",
                    ),
                ),
                (
                    "economic_context",
                    models.TextField(
                        blank=True,
                        help_text="支付能力、取药便利性等补充信息",
                        null=True,
                        verbose_name="经济情况",
                    ),
                ),
                (
                    "health_expectations",
                    models.TextField(
                        blank=True,
                        help_text="患者对本次服务的目标和期望",
                        null=True,
                        verbose_name="健康期望",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="问诊补充记录",
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="问诊完成时间",
                        null=True,
                        verbose_name="完成时间",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "service_case",
                    models.OneToOneField(
                        help_text="对应的 MTM 服务单",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview",
                        to="mtm.mtmservicecase",
                        verbose_name="服务单",
                    ),
                ),
            ],
            options={
                "verbose_name": "MTM问诊",
                "verbose_name_plural": "MTM问诊",
                "db_table": "mtm_interviews",
            },
        ),
        migrations.CreateModel(
            name="MTMFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "follow_up_time",
                    models.DateTimeField(
                        help_text="本次随访计划或实际发生时间", verbose_name="随访时间"
                    ),
                ),
                (
                    "follow_up_method",
                    models.CharField(
                        choices=[
                            ("phone", "电话"),
                            ("in_person", "面谈"),
                            ("video", "视频"),
                            ("wechat", "微信"),
                            ("other", "其他"),
                        ],
                        default="phone",
                        help_text="本次随访使用的方式",
                        max_length=20,
                        verbose_name="随访方式",
                    ),
                ),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("completed", "已完成"),
                            ("missed", "未完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        help_text="本次随访执行结果",
                        max_length=20,
                        verbose_name="执行情况",
                    ),
                ),
                (
                    "risk_change",
                    models.CharField(
                        choices=[
                            ("improved", "改善"),
                            ("stable", "稳定"),
                            ("worsened", "恶化"),
                            ("unknown", "未知"),
                        ],
                        default="unknown",
                        help_text="本次随访后风险变化情况",
                        max_length=20,
                        verbose_name="风险变化",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="本次随访的主要结论",
                        null=True,
                        verbose_name="随访总结",
                    ),
                ),
                (
                    "next_follow_up_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="建议的下一次随访时间",
                        null=True,
                        verbose_name="下次随访时间",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "service_case",
                    models.ForeignKey(
                        help_text="对应的 MTM 服务单",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="mtm.mtmservicecase",
                        verbose_name="服务单",
                    ),
                ),
            ],
            options={
                "verbose_name": "MTM随访",
                "verbose_name_plural": "MTM随访",
                "db_table": "mtm_follow_ups",
                "ordering": ["-follow_up_time", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MTMAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appropriateness_score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="药物选择适宜性评分",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="适宜性评分",
                    ),
                ),
                (
                    "effectiveness_score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="治疗有效性评分",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="有效性评分",
                    ),
                ),
                (
                    "safety_score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="安全风险评分",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="安全性评分",
                    ),
                ),
                (
                    "adherence_score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="依从性评分",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="依从性评分",
                    ),
                ),
                (
                    "economic_score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="经济负担评分",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="经济性评分",
                    ),
                ),
                (
                    "problem_list",
                    models.JSONField(
                        default=list,
                        help_text="结构化药物治疗问题列表",
                        verbose_name="问题清单",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="本次评估的总结说明",
                        null=True,
                        verbose_name="评估总结",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        default="medium",
                        help_text="评估综合风险等级",
                        max_length=10,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="评估完成时间",
                        null=True,
                        verbose_name="完成时间",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "service_case",
                    models.OneToOneField(
                        help_text="对应的 MTM 服务单",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment",
                        to="mtm.mtmservicecase",
                        verbose_name="服务单",
                    ),
                ),
            ],
            options={
                "verbose_name": "MTM评估",
                "verbose_name_plural": "MTM评估",
                "db_table": "mtm_assessments",
            },
        ),
        migrations.AddIndex(
            model_name="mtmservicecase",
            index=models.Index(fields=["case_number"], name="idx_mtm_case_number"),
        ),
        migrations.AddIndex(
            model_name="mtmservicecase",
            index=models.Index(fields=["patient"], name="idx_mtm_case_patient"),
        ),
        migrations.AddIndex(
            model_name="mtmservicecase",
            index=models.Index(
                fields=["assigned_pharmacist"], name="idx_mtm_case_pharm"
            ),
        ),
        migrations.AddIndex(
            model_name="mtmservicecase",
            index=models.Index(fields=["status"], name="idx_mtm_case_status"),
        ),
        migrations.AddIndex(
            model_name="mtmservicecase",
            index=models.Index(fields=["trigger_source"], name="idx_mtm_case_trigger"),
        ),
        migrations.AddIndex(
            model_name="mtmservicecase",
            index=models.Index(fields=["created_at"], name="idx_mtm_case_created"),
        ),
        migrations.AddIndex(
            model_name="mtmplan",
            index=models.Index(fields=["priority"], name="idx_mtm_plan_priority"),
        ),
        migrations.AddIndex(
            model_name="mtmplan",
            index=models.Index(
                fields=["patient_confirmation_status"], name="idx_mtm_plan_confirm"
            ),
        ),
        migrations.AddIndex(
            model_name="mtmfollowup",
            index=models.Index(fields=["service_case"], name="idx_mtm_follow_case"),
        ),
        migrations.AddIndex(
            model_name="mtmfollowup",
            index=models.Index(fields=["follow_up_time"], name="idx_mtm_follow_time"),
        ),
        migrations.AddIndex(
            model_name="mtmfollowup",
            index=models.Index(fields=["execution_status"], name="idx_mtm_follow_exec"),
        ),
        migrations.AddIndex(
            model_name="mtmassessment",
            index=models.Index(fields=["risk_level"], name="idx_mtm_assess_risk"),
        ),
        migrations.AddIndex(
            model_name="mtmassessment",
            index=models.Index(fields=["completed_at"], name="idx_mtm_assess_done"),
        ),
    ]
