# Generated by Django 4.2.16 on 2026-04-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mtm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mtmplan",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, help_text="干预计划完成起草的时间", null=True, verbose_name="完成时间"
            ),
        ),
    ]
