# Generated by Django 4.2.16 on 2025-09-02 04:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("medicines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_time",
                    models.TimeField(help_text="每日提醒的具体时间", verbose_name="提醒时间"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "每日"),
                            ("twice_daily", "每日两次"),
                            ("three_times_daily", "每日三次"),
                            ("four_times_daily", "每日四次"),
                            ("every_other_day", "隔日"),
                            ("weekly", "每周"),
                            ("as_needed", "按需"),
                            ("custom", "自定义"),
                        ],
                        default="daily",
                        help_text="用药提醒的频率",
                        max_length=20,
                        verbose_name="提醒频率",
                    ),
                ),
                (
                    "dosage",
                    models.PositiveIntegerField(
                        help_text="每次服用的药品数量",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="每次剂量",
                    ),
                ),
                (
                    "dosage_unit",
                    models.CharField(
                        choices=[
                            ("tablet", "片"),
                            ("capsule", "粒"),
                            ("ml", "毫升"),
                            ("mg", "毫克"),
                            ("drop", "滴"),
                            ("spray", "喷"),
                            ("other", "其他"),
                        ],
                        default="tablet",
                        help_text="剂量的计量单位",
                        max_length=20,
                        verbose_name="剂量单位",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="提醒是否处于激活状态", verbose_name="是否激活"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="自定义提醒标题",
                        max_length=100,
                        null=True,
                        verbose_name="提醒标题",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="自定义提醒内容", null=True, verbose_name="提醒内容"
                    ),
                ),
                (
                    "notification_types",
                    models.JSONField(
                        default=list, help_text="提醒的通知方式列表", verbose_name="提醒方式"
                    ),
                ),
                (
                    "advance_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="提前多少分钟进行提醒",
                        validators=[django.core.validators.MaxValueValidator(1440)],
                        verbose_name="提前提醒时间（分钟）",
                    ),
                ),
                (
                    "repeat_interval",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="重复提醒的间隔时间，0表示不重复",
                        validators=[django.core.validators.MaxValueValidator(60)],
                        verbose_name="重复提醒间隔（分钟）",
                    ),
                ),
                (
                    "max_repeats",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="最多重复提醒的次数",
                        validators=[django.core.validators.MaxValueValidator(10)],
                        verbose_name="最大重复次数",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="提醒开始的日期",
                        verbose_name="开始日期",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="提醒结束的日期，为空表示长期提醒",
                        null=True,
                        verbose_name="结束日期",
                    ),
                ),
                (
                    "weekdays",
                    models.JSONField(
                        default=list,
                        help_text="自定义频率时的星期设置，1-7表示周一到周日",
                        verbose_name="星期设置",
                    ),
                ),
                (
                    "meal_timing",
                    models.CharField(
                        choices=[
                            ("before_meal", "餐前"),
                            ("after_meal", "餐后"),
                            ("with_meal", "餐中"),
                            ("empty_stomach", "空腹"),
                            ("anytime", "任意时间"),
                        ],
                        default="anytime",
                        help_text="相对于用餐时间的服药时机",
                        max_length=20,
                        verbose_name="餐前餐后",
                    ),
                ),
                (
                    "special_instructions",
                    models.TextField(
                        blank=True,
                        help_text="特殊的用药说明或注意事项",
                        null=True,
                        verbose_name="特殊说明",
                    ),
                ),
                (
                    "last_reminded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="最后一次发送提醒的时间",
                        null=True,
                        verbose_name="最后提醒时间",
                    ),
                ),
                (
                    "reminder_count",
                    models.PositiveIntegerField(
                        default=0, help_text="累计提醒次数", verbose_name="提醒次数"
                    ),
                ),
                (
                    "response_count",
                    models.PositiveIntegerField(
                        default=0, help_text="用户响应提醒的次数", verbose_name="响应次数"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="提醒创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="提醒最后更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        help_text="需要提醒的药品",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="medicines.medicine",
                        verbose_name="药品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="提醒所属用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="users.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用药提醒",
                "verbose_name_plural": "用药提醒",
                "db_table": "reminders",
                "ordering": ["reminder_time"],
                "indexes": [
                    models.Index(fields=["user_id"], name="idx_reminders_user_id"),
                    models.Index(
                        fields=["medicine_id"], name="idx_reminders_medicine_id"
                    ),
                    models.Index(fields=["is_active"], name="idx_reminders_is_active"),
                    models.Index(fields=["reminder_time"], name="idx_reminders_time"),
                    models.Index(
                        fields=["start_date"], name="idx_reminders_start_date"
                    ),
                    models.Index(fields=["end_date"], name="idx_reminders_end_date"),
                    models.Index(
                        fields=["user_id", "is_active"],
                        name="idx_reminders_user_active",
                    ),
                ],
            },
        ),
    ]
