# Generated by Django 4.2.16 on 2025-09-02 06:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("reminders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="统计的日期", verbose_name="统计日期")),
                (
                    "scheduled_count",
                    models.PositiveIntegerField(
                        default=0, help_text="当日计划的提醒数量", verbose_name="计划提醒数"
                    ),
                ),
                (
                    "sent_count",
                    models.PositiveIntegerField(
                        default=0, help_text="当日实际发送的提醒数量", verbose_name="实际发送数"
                    ),
                ),
                (
                    "responded_count",
                    models.PositiveIntegerField(
                        default=0, help_text="当日用户响应的提醒数量", verbose_name="用户响应数"
                    ),
                ),
                (
                    "taken_count",
                    models.PositiveIntegerField(
                        default=0, help_text="当日标记为已服用的数量", verbose_name="已服用数"
                    ),
                ),
                (
                    "skipped_count",
                    models.PositiveIntegerField(
                        default=0, help_text="当日跳过的提醒数量", verbose_name="跳过数"
                    ),
                ),
                (
                    "delayed_count",
                    models.PositiveIntegerField(
                        default=0, help_text="当日延迟的提醒数量", verbose_name="延迟数"
                    ),
                ),
                (
                    "ignored_count",
                    models.PositiveIntegerField(
                        default=0, help_text="当日忽略的提醒数量", verbose_name="忽略数"
                    ),
                ),
                (
                    "avg_response_time",
                    models.FloatField(
                        default=0, help_text="当日平均响应时间", verbose_name="平均响应时间（分钟）"
                    ),
                ),
                (
                    "response_rate",
                    models.FloatField(
                        default=0, help_text="当日的响应率百分比", verbose_name="响应率（%）"
                    ),
                ),
                (
                    "adherence_rate",
                    models.FloatField(
                        default=0, help_text="当日的服药率百分比", verbose_name="服药率（%）"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="统计创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="统计更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="统计的用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_stats",
                        to="users.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "提醒统计",
                "verbose_name_plural": "提醒统计",
                "db_table": "reminder_stats",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["user_id"], name="idx_reminder_stats_user"),
                    models.Index(fields=["date"], name="idx_reminder_stats_date"),
                    models.Index(
                        fields=["user_id", "date"], name="idx_reminder_stats_user_date"
                    ),
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="ReminderHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="提醒发送的时间",
                        verbose_name="发送时间",
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(help_text="原计划的提醒时间", verbose_name="计划时间"),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("scheduled", "定时提醒"),
                            ("repeat", "重复提醒"),
                            ("manual", "手动提醒"),
                            ("makeup", "补服提醒"),
                        ],
                        default="scheduled",
                        help_text="提醒的类型",
                        max_length=20,
                        verbose_name="提醒类型",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="发送的提醒标题", max_length=200, verbose_name="提醒标题"
                    ),
                ),
                ("message", models.TextField(help_text="发送的提醒内容", verbose_name="提醒内容")),
                (
                    "notification_methods",
                    models.JSONField(
                        default=list, help_text="使用的通知方式列表", verbose_name="通知方式"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "已发送"),
                            ("failed", "发送失败"),
                            ("pending", "待发送"),
                            ("cancelled", "已取消"),
                        ],
                        default="sent",
                        help_text="提醒的发送状态",
                        max_length=20,
                        verbose_name="发送状态",
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="用户响应提醒的时间",
                        null=True,
                        verbose_name="响应时间",
                    ),
                ),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("taken", "已服用"),
                            ("skipped", "跳过"),
                            ("delayed", "延迟"),
                            ("ignored", "忽略"),
                            ("no_response", "无响应"),
                        ],
                        default="no_response",
                        help_text="用户的响应类型",
                        max_length=20,
                        verbose_name="响应类型",
                    ),
                ),
                (
                    "response_delay_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="从发送到响应的延迟时间",
                        null=True,
                        verbose_name="响应延迟（分钟）",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="额外的备注信息", null=True, verbose_name="备注"
                    ),
                ),
                (
                    "device_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="发送通知时的设备信息",
                        verbose_name="设备信息",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="记录创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "reminder",
                    models.ForeignKey(
                        help_text="关联的提醒设置",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_records",
                        to="reminders.reminder",
                        verbose_name="提醒",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="提醒的用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_history",
                        to="users.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "提醒历史记录",
                "verbose_name_plural": "提醒历史记录",
                "db_table": "reminder_history",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(fields=["user_id"], name="idx_reminder_history_user"),
                    models.Index(
                        fields=["reminder_id"], name="idx_reminder_history_reminder"
                    ),
                    models.Index(
                        fields=["sent_at"], name="idx_reminder_history_sent_at"
                    ),
                    models.Index(fields=["status"], name="idx_reminder_history_status"),
                    models.Index(
                        fields=["response_type"], name="idx_reminder_history_response"
                    ),
                    models.Index(
                        fields=["user_id", "sent_at"],
                        name="idx_reminder_history_user_sent",
                    ),
                ],
            },
        ),
    ]
