# Generated by Django 4.2.16 on 2025-09-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reminders", "0002_reminderstats_reminderhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="meal_timing",
            field=models.CharField(
                choices=[
                    ("before_meal", "餐前"),
                    ("after_meal", "餐后"),
                    ("with_meal", "餐中"),
                    ("empty_stomach", "空腹"),
                    ("anytime", "任意时间"),
                    ("before_breakfast", "早饭前"),
                    ("after_dinner", "晚饭后"),
                    ("before_bed", "睡前"),
                ],
                default="anytime",
                help_text="相对于用餐时间的服药时机",
                max_length=20,
                verbose_name="用药时机",
            ),
        ),
    ]
