# Redis配置文件
# 设置密码
requirepass ghp880218

# 基本配置
port 6379
bind 127.0.0.1
timeout 0

# 日志配置
loglevel notice
logfile ""

# 数据库配置
databases 16

# 持久化配置
save 900 1
save 300 10
save 60 10000

stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir ./

# 内存管理
maxmemory-policy allkeys-lru