# Generated by Django 4.2.16 on 2025-11-10 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.URLField(unique=True, verbose_name="订阅端点")),
                (
                    "keys",
                    models.JSONField(
                        default=dict,
                        help_text="包含 p256dh 与 auth 字段",
                        verbose_name="密钥信息",
                    ),
                ),
                (
                    "expiration_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="过期时间"),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="UA"
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="时区"
                    ),
                ),
                (
                    "app",
                    models.CharField(
                        default="mtm-helper", max_length=64, verbose_name="应用标识"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否有效")),
                (
                    "last_sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后发送时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "Push订阅",
                "verbose_name_plural": "Push订阅",
                "db_table": "push_subscriptions",
                "indexes": [
                    models.Index(fields=["user"], name="idx_push_sub_user"),
                    models.Index(fields=["is_active"], name="idx_push_sub_active"),
                    models.Index(fields=["updated_at"], name="idx_push_sub_updated"),
                ],
            },
        ),
    ]
