# Generated by Django 4.2.16 on 2026-04-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_pushsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushsubscription",
            name="endpoint",
            field=models.URLField(max_length=512, unique=True, verbose_name="订阅端点"),
        ),
    ]
