# Generated by Django 4.2.16 on 2026-04-20 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("pharmacist", "药师"),
                            ("patient", "患者"),
                            ("default", "默认"),
                        ],
                        max_length=50,
                        verbose_name="角色",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        help_text="例如: navigate, fill_form, submit",
                        max_length=50,
                        verbose_name="动作类型",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ask", "询问 (Ask)"),
                            ("allow", "允许 (Allow)"),
                            ("deny", "拒绝 (Deny)"),
                        ],
                        default="ask",
                        max_length=10,
                        verbose_name="权限状态",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Agent 权限配置",
                "verbose_name_plural": "Agent 权限配置",
                "db_table": "core_agent_permission",
                "unique_together": {("role", "action_type")},
            },
        ),
        migrations.CreateModel(
            name="SessionMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=128)),
                ("summary", models.TextField(blank=True, verbose_name="摘要")),
                (
                    "messages",
                    models.JSONField(blank=True, default=list, verbose_name="消息列表"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "会话记忆",
                "verbose_name_plural": "会话记忆",
                "db_table": "core_session_memory",
                "unique_together": {("user", "session_id")},
            },
        ),
    ]
