# Generated by Django 4.2.16 on 2025-09-02 04:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("medicines", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="用药计划的名称", max_length=100, verbose_name="计划名称"
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("long_term", "长期用药"),
                            ("short_term", "短期用药"),
                            ("acute", "急性治疗"),
                            ("chronic", "慢性管理"),
                            ("preventive", "预防用药"),
                            ("rehabilitation", "康复治疗"),
                        ],
                        default="short_term",
                        help_text="用药计划的类型",
                        max_length=20,
                        verbose_name="计划类型",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="计划开始执行的日期", verbose_name="开始日期"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="计划结束日期，为空表示长期计划",
                        null=True,
                        verbose_name="结束日期",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="用药计划的详细描述",
                        null=True,
                        verbose_name="计划描述",
                    ),
                ),
                (
                    "treatment_goal",
                    models.TextField(
                        blank=True,
                        help_text="此用药计划要达到的治疗目标",
                        null=True,
                        verbose_name="治疗目标",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="计划是否处于激活状态", verbose_name="是否激活"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("urgent", "紧急"),
                        ],
                        default="medium",
                        help_text="计划的优先级",
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("doctor", "医生开具"),
                            ("self", "自行制定"),
                            ("pharmacist", "药师建议"),
                            ("import", "导入"),
                            ("template", "模板创建"),
                        ],
                        default="self",
                        help_text="计划的创建来源",
                        max_length=20,
                        verbose_name="创建来源",
                    ),
                ),
                (
                    "doctor_name",
                    models.CharField(
                        blank=True,
                        help_text="开具此计划的医生姓名",
                        max_length=50,
                        null=True,
                        verbose_name="医生姓名",
                    ),
                ),
                (
                    "hospital_name",
                    models.CharField(
                        blank=True,
                        help_text="开具此计划的医院名称",
                        max_length=100,
                        null=True,
                        verbose_name="医院名称",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="开具此计划的科室",
                        max_length=50,
                        null=True,
                        verbose_name="科室",
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(
                        blank=True, help_text="相关的诊断信息", null=True, verbose_name="诊断信息"
                    ),
                ),
                (
                    "precautions",
                    models.TextField(
                        blank=True,
                        help_text="用药过程中的注意事项",
                        null=True,
                        verbose_name="注意事项",
                    ),
                ),
                (
                    "side_effects_monitoring",
                    models.TextField(
                        blank=True,
                        help_text="需要监控的副作用",
                        null=True,
                        verbose_name="副作用监控",
                    ),
                ),
                (
                    "review_date",
                    models.DateField(
                        blank=True, help_text="建议的复查时间", null=True, verbose_name="复查时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "执行中"),
                            ("paused", "暂停"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="active",
                        help_text="当前计划的状态",
                        max_length=20,
                        verbose_name="计划状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="计划创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="计划最后更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="计划所属用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_plans",
                        to="users.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用药计划",
                "verbose_name_plural": "用药计划",
                "db_table": "medication_plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanMedicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_dosage",
                    models.PositiveIntegerField(
                        help_text="每日总剂量",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="每日剂量",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once_daily", "每日一次"),
                            ("twice_daily", "每日两次"),
                            ("three_times_daily", "每日三次"),
                            ("four_times_daily", "每日四次"),
                            ("every_other_day", "隔日一次"),
                            ("weekly", "每周一次"),
                            ("as_needed", "按需服用"),
                            ("custom", "自定义"),
                        ],
                        default="once_daily",
                        help_text="药品的服用频率",
                        max_length=20,
                        verbose_name="服用频率",
                    ),
                ),
                (
                    "single_dose",
                    models.PositiveIntegerField(
                        help_text="每次服用的剂量",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="单次剂量",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="具体的用药指导说明",
                        null=True,
                        verbose_name="用药说明",
                    ),
                ),
                (
                    "administration_times",
                    models.JSONField(
                        default=list, help_text="每日具体的服用时间列表", verbose_name="服用时间"
                    ),
                ),
                (
                    "meal_timing",
                    models.CharField(
                        choices=[
                            ("before_meal", "餐前"),
                            ("after_meal", "餐后"),
                            ("with_meal", "餐中"),
                            ("empty_stomach", "空腹"),
                            ("anytime", "任意时间"),
                        ],
                        default="anytime",
                        help_text="相对于用餐时间的服药时机",
                        max_length=20,
                        verbose_name="餐前餐后",
                    ),
                ),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True,
                        help_text="特殊的服药要求或注意事项",
                        null=True,
                        verbose_name="特殊要求",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, help_text="是否为必需药品", verbose_name="是否必需"
                    ),
                ),
                (
                    "start_day",
                    models.PositiveIntegerField(
                        default=1, help_text="相对于计划开始的第几天开始服用", verbose_name="开始天数"
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="此药品的服用天数，为空表示跟随计划",
                        null=True,
                        verbose_name="持续天数",
                    ),
                ),
                (
                    "dosage_adjustments",
                    models.JSONField(
                        default=list, help_text="剂量调整的历史记录", verbose_name="剂量调整记录"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="记录创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="记录最后更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "alternative_medicine",
                    models.ForeignKey(
                        blank=True,
                        help_text="可替代的药品",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alternative_for",
                        to="medicines.medicine",
                        verbose_name="替代药品",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        help_text="计划中的药品",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_medicines",
                        to="medicines.medicine",
                        verbose_name="药品",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="所属的用药计划",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_medicines",
                        to="plans.medicationplan",
                        verbose_name="用药计划",
                    ),
                ),
            ],
            options={
                "verbose_name": "计划药品",
                "verbose_name_plural": "计划药品",
                "db_table": "plan_medicines",
                "ordering": ["start_day", "created_at"],
                "indexes": [
                    models.Index(fields=["plan_id"], name="idx_plan_medicines_plan_id"),
                    models.Index(
                        fields=["medicine_id"], name="idx_plan_medicines_medicine_id"
                    ),
                    models.Index(
                        fields=["frequency"], name="idx_plan_medicines_frequency"
                    ),
                    models.Index(
                        fields=["is_required"], name="idx_plan_medicines_required"
                    ),
                ],
                "unique_together": {("plan", "medicine")},
            },
        ),
        migrations.AddIndex(
            model_name="medicationplan",
            index=models.Index(fields=["user"], name="idx_med_plan_user"),
        ),
        migrations.AddIndex(
            model_name="medicationplan",
            index=models.Index(fields=["start_date"], name="idx_med_plan_start"),
        ),
        migrations.AddIndex(
            model_name="medicationplan",
            index=models.Index(fields=["end_date"], name="idx_med_plan_end"),
        ),
        migrations.AddIndex(
            model_name="medicationplan",
            index=models.Index(fields=["status"], name="idx_med_plan_status"),
        ),
        migrations.AddIndex(
            model_name="medicationplan",
            index=models.Index(fields=["created_at"], name="idx_med_plan_created"),
        ),
    ]
