# Generated by Django 4.2.16 on 2026-02-21 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "创建"),
                            ("UPDATE", "更新"),
                            ("DELETE", "删除"),
                            ("ACCESS", "访问"),
                            ("LOGIN", "登录"),
                            ("LOGOUT", "登出"),
                            ("EXPORT", "导出"),
                            ("OTHER", "其他"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        help_text="被操作对象的模型名称", max_length=100, verbose_name="资源类型"
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="资源ID"
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="操作详情"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="用户代理"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="操作时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "审计日志",
                "verbose_name_plural": "审计日志",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="audit_audit_user_id_292c79_idx"
                    ),
                    models.Index(
                        fields=["action"], name="audit_audit_action_86e815_idx"
                    ),
                    models.Index(
                        fields=["resource_type"], name="audit_audit_resourc_92cef7_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="audit_audit_created_2c1626_idx"
                    ),
                ],
            },
        ),
    ]
