# Generated by Django 4.2.16 on 2025-09-02 04:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("medicines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taken_at",
                    models.DateTimeField(help_text="实际服药的时间", verbose_name="服药时间"),
                ),
                (
                    "quantity_taken",
                    models.PositiveIntegerField(
                        help_text="本次服用的药品数量",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="服药数量",
                    ),
                ),
                (
                    "administration_method",
                    models.CharField(
                        choices=[
                            ("oral", "口服"),
                            ("injection", "注射"),
                            ("topical", "外用"),
                            ("inhalation", "吸入"),
                            ("sublingual", "舌下含服"),
                            ("rectal", "直肠给药"),
                            ("other", "其他"),
                        ],
                        default="oral",
                        help_text="药品的给药方式",
                        max_length=20,
                        verbose_name="服药方式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("taken", "已服用"),
                            ("missed", "漏服"),
                            ("delayed", "延迟服用"),
                            ("partial", "部分服用"),
                        ],
                        default="taken",
                        help_text="本次服药的状态",
                        max_length=20,
                        verbose_name="服药状态",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="服药时的备注信息，如副作用、感受等",
                        null=True,
                        verbose_name="服药备注",
                    ),
                ),
                (
                    "symptom_score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="服药前症状严重程度评分（1-10分）",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="症状评分",
                    ),
                ),
                (
                    "effectiveness_score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="服药后效果评分（1-10分）",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="效果评分",
                    ),
                ),
                (
                    "side_effects",
                    models.TextField(
                        blank=True,
                        help_text="服药后出现的副作用描述",
                        null=True,
                        verbose_name="副作用",
                    ),
                ),
                (
                    "is_on_time",
                    models.BooleanField(
                        default=True, help_text="是否按照预定时间服药", verbose_name="是否按时服药"
                    ),
                ),
                (
                    "delay_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="相对于预定时间的延迟分钟数",
                        null=True,
                        verbose_name="延迟时间（分钟）",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "手动记录"),
                            ("reminder", "提醒记录"),
                            ("import", "导入记录"),
                            ("auto", "自动记录"),
                        ],
                        default="manual",
                        help_text="记录的创建来源",
                        max_length=20,
                        verbose_name="记录来源",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="记录创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="记录最后更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        help_text="服用的药品",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_records",
                        to="medicines.medicine",
                        verbose_name="药品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="用药记录所属用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_records",
                        to="users.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用药记录",
                "verbose_name_plural": "用药记录",
                "db_table": "medication_records",
                "ordering": ["-taken_at"],
                "indexes": [
                    models.Index(fields=["user"], name="idx_med_rec_user"),
                    models.Index(fields=["medicine"], name="idx_med_rec_medicine"),
                    models.Index(fields=["taken_at"], name="idx_med_rec_taken"),
                    models.Index(
                        fields=["user", "taken_at"], name="idx_med_rec_user_taken"
                    ),
                    models.Index(fields=["created_at"], name="idx_med_rec_created"),
                ],
            },
        ),
    ]
