# Generated by Django 4.2.16 on 2025-09-07 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicationrecord",
            name="effectiveness_score",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="服药后效果评分（0-10分）",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="效果评分",
            ),
        ),
    ]
